[servers]
server01 ansible_host=172.28.3.159 ansible_user=dev 
server02 ansible_host=172.28.3.143 
server03 ansible_host=172.28.3.165

[servers:vars]
ansible_user=root
ansible_password='{{ vault_server_password }}'
ansible_python_interpreter=/usr/bin/python3
